# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestMail():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mail(self):
    self.driver.get("https://mail.qq.com/cgi-bin/frame_html?sid=G1PSri7LVo02Zz9i&r=7e6621d8ee3ca67b6700de6fd646980e")
    self.driver.set_window_size(1050, 717)
    self.driver.find_element(By.ID, "composebtn").click()
    element = self.driver.find_element(By.ID, "readmailbtn_link")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.ID, "toAreaCtrl").click()
    self.driver.find_element(By.ID, "lm157261263917409116493329824249searchtext").click()
    self.driver.find_element(By.ID, "lm157261263917409116493329824249searchtext").send_keys("唐")
    self.driver.find_element(By.CSS_SELECTOR, ".lm_email").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".lm_email")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "subject").click()
    self.driver.find_element(By.ID, "subject").send_keys("这是一封测试邮件")
    self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
