# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("https://mail.qq.com/cgi-bin/loginpage?autologin=n&errtype=4&clientuin=1490780232&t=&vt=passport&param=&sp=5f3ca1104ee0c02MTU3MjYyNTM0OA&tfcont=22%20serialization%3A%3Aarchive%205%200%200%206%200%200%200%208%20authtype%201%204%207%20spcache%2029%205f3ca1104ee0c02MTU3MjYyNTM0OA%202%20sp%2029%205f3ca1104ee0c02MTU3MjYyNTM0OA%209%20clientuin%2010%201490780232%206%20domain%206%20qq.com%202%20vm%203%20wsk&r=b8336d8c8bb5e1ae78f93a640ad783dd")
    self.driver.set_window_size(1050, 717)
    self.driver.find_element(By.ID, "btlogin").click()
    element = self.driver.find_element(By.ID, "composebtn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "composebtn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "composebtn").click()
    element = self.driver.find_element(By.ID, "composebtn")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.CSS_SELECTOR, "#sendtimepadding > div:nth-child(3)").click()
    self.driver.find_element(By.ID, "subject").click()
    self.driver.find_element(By.ID, "subject").send_keys("测试邮件")
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_gray:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
